### ISSUE TITLE
SVG file cannot be read by Inkscape

### ISSUE THREAD

**Issue by SimonDesbonnets** [agordon/d3export_demo#1]
Hello,

I'm a very beginner in d3js. I'm using it to create nice diagrams but not for the web. I'm using your code to export them in high resolution for large printing.

Everything working well excepting that the svg file cannot be read by inkscape.

Is it a known limitation ? are you working on ?

Anyway, you've done a nice job !

**Comment by agordon** [comment]
Good catch. Should be fixed now.

**Comment by SimonDesbonnets** [comment]
Yes it works now !
Thanks for your quick answer.

And I'm glad that I've created your first issue ;-)
