### ISSUE TITLE
not working with embedded svg?

### ISSUE THREAD

**Issue by er2es** [agordon/d3export_demo#2]
the html:

``` javascript
<embed src="svg/moMegye.svg" id="svgmap" width="100%" height="100%" wmode="transparent" type="image/svg+xml">
```

the javascript:

``` javascript

function submit_download_form(output_format)
{

    var tmp = document.getElementById("mainmap");
    var svg = tmp.getElementsByTagName("[??????]")[0];
    var svg_xml = (new XMLSerializer).serializeToString(svg);

    var form = document.getElementById("svgform");
    form['output_format'].value = output_format;
    form['data'].value = svg_xml ;
    form.submit();
}

$(document).ready(function() {

    $("#save_as_png").click(function() { submit_download_form("png"); });

});

```

result on download.pl

``` javascript
Missing 'data' parameter at ***********/download.pl line 48.
```

**Comment by agordon** [comment]
If you've changed the HTML code, you'll probably need to change the Javascript accordingly.
Without knowing all the relevant HTML code, I can't fully help (e.g. what is the `mainmap` tag in the javascript?).
But from a glance, I'd guess that if your embedded SVG tag has an id of `svgmap`, you'll need to change the Javascript code to have `var svg = document.getElementById("svgmap")` .

I'd first start by debugging the javascript on the client side with Chrome or Firefox, and see what is the content of the `svg` and `form` variables - to see if you get the correct values.
