### ISSUE TITLE
Any ideas how I could run this on heroku?

### ISSUE THREAD

**Issue by xypaul** [agordon/d3export_demo#4]
I am currently running my website on heroku with node.js

Do you have any idea how I could make this run on their platform?

**Comment by agordon** [comment]
I'm not familiar enough with Heroku or node.

If you just want to allow downloading as "svg", the code is simple (just accept the SVG content as  <FORM> POST request, see the perl code for example).

If you want to convert SVG to PDF, then it depends on whether you can install 'rsvg-convert' binary on Heruko, or does node.js have built-in libraries to convert SVG to PDF.

The  CGI code is obviously not perl-specific, an example of equivalent functionality in Python+Flask is here: https://github.com/mgymrek/pybamview/commit/c26de4dde7316d557ccbe9ee4159525950898bea#diff-070773797d6114c159703d8a18c749a2
