### ISSUE TITLE
ASP MVC Throwing Error 

### ISSUE THREAD

**Issue by ghost** [agordon/d3export_demo#7]
This is a great tool! However, I'm trying to recreate this in an MVC environment and I'm getting:
HTTP Error 405.0 - Method Not Allowed
The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.

This seems to be happen when the hidden svgform is being submitted. Any ideas how to get this to work in IIS?

EDIT: I see it's a Perl file. Am I only able to use this demo on an Apache server?

**Comment by agordon** [comment]
Hello,

This seems to be a configuration error on the server-side.
The demo setup requires the server to be able to run a CGI script (it doesn't matter that the script is written in Perl). Apache can do this. Many other web can run CGI scripts as well (e.g. lighttpd). Others can not (e.g. nginx) and require additional settings.
The README file contains links to similar implementation in other programming languages, perhaps that will be easier for to to deploy.

In anycase, the perl script is just a thin wrapper around the `rsvg-convert` command-line program, so you might just re-write it in whichever environment you prefer.

**Comment by ghost** [comment]
Thanks!. Looking into it now.
