### ISSUE TITLE
Error when running the demo on local server

### ISSUE THREAD

**Issue by nuwee-de** [agordon/d3export_demo#8]
I tried to run the code on XAMPP and exporting as a svg works perfectly. But when I try to export as a pdf or png this error is thrown
"rsvg-convert -o '\xampp\tmp\d3export.out.c9sWxKK' -z '10' -f 'png' '\xampp\tmp\d3export.svg.sxxMJEX'" unexpectedly returned exit value 1 at (eval 79) line 13.
 at C:/xampp/htdocs/d3e/download.pl line 81

**Comment by agordon** [comment]
1. are you sure you have `rsvg-convert` installed on the system, and available on the PATH ?
2. Does the command work as-is if you copy&paste it in the terminal ?
   `rsvg-convert -o '\xampp\tmp\d3export.out.c9sWxKK' -z '10' -f 'png' '\xampp\tmp\d3export.svg.sxxMJEX'`
   If it doesn't, then it clearly won't work from the perl script, and you'll need to fix it.
